/*
 *  @file KeyCodes.h
 */


#define KEY_CODE_RETURN (36)
#define KEY_CODE_ENTER (76)
#define KEY_CODE_FORWARD_DELETE (117)
#define KEY_CODE_BACKWARD_DELETE (51)
#define KEY_CODE_ESCAPE (53)
#define KEY_CODE_SPACE_BAR (49)
#define KEY_CODE_LEFT_ARROW (123)
#define KEY_CODE_RIGHT_ARROW (124)
#define KEY_CODE_DOWN_ARROW (125)
#define KEY_CODE_UP_ARROW (126)
#define KEY_CODE_PAGE_UP (116)
#define KEY_CODE_PAGE_DOWN (121)
